### ISSUE TITLE
Actualizar la base de datos

### ISSUE THREAD

**Issue by devarops** [IslasGECI/tamanio-poblacional-aves-marinas#5]
Actualizar el _hash_ y repositorio de los datos. Actualmente está usando el de `datapackages`

**Comment by devarops** [comment]
@islasfernando está trabajando en esto en [GECI-69](https://app.gitkraken.com/glo/view/card/98dfb39d0942486fbadbd72191f2a082)

**Comment by GenaroVel** [comment]
Este Issue ya quedó, [aquí ](https://github.com/IslasGECI/tamanio-poblacional-aves-marinas/actions/runs/145399936) podemos ver el Actions del _merge_ de la rama `feature/actualiza_base_datos`

**Comment by devarops** [comment]
Ya quedó en #9
